name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev autoconf libtool pkg-config zlib1g-dev cmake openjdk-17-jdk-headless python3-pip zip unzip lld

      - name: Setup Buildozer
        run: |
          pip3 install --user --upgrade buildozer cython==0.29.33 sh

      - name: Accept Android Licenses & Build
        run: |
          export PATH=$PATH:~/.local/bin
          # 1. Заставляем Buildozer скачать SDK
          buildozer android precaches || true
          
          # 2. Хитрый поиск: находим sdkmanager, где бы он ни прятался, и принимаем ВСЕ лицензии
          find $HOME/.buildozer/ -name "sdkmanager" -exec sh -c 'yes | {} --licenses' \; || true
          
          # 3. Финальный запуск сборки
          yes | buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
