name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev autoconf libtool pkg-config zlib1g-dev cmake openjdk-17-jdk-headless python3-pip zip unzip lld

      - name: Setup Buildozer
        run: |
          pip3 install --user --upgrade buildozer cython==0.29.33 sh

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Эта команда автоматически введет "yes" на любые вопросы лицензий Android
          yes | buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
